<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/10/16
 * Time: 11:36
 */

namespace Model;


use es\EsModel;

class MemberModel extends EsModel
{

    public function addDoc($id, $doc, $index, $type)
    {
        parent::addDoc($id, $doc, $index, $type); // TODO: Change the autogenerated stub
    }

    public function deleteDoc($id, $index_name, $type_name)
    {
        parent::deleteDoc($id, $index_name, $type_name); // TODO: Change the autogenerated stub
    }

    public function updateDoc($id, $index, $type)
    {
        parent::updateDoc($id, $index, $type); // TODO: Change the autogenerated stub
    }

    public function setMapping($type, $index)
    {
        parent::setMapping($type, $index); // TODO: Change the autogenerated stub
    }

    /**
     * 获取对应索引的映射
     * @param null $index
     * @param null $type
     * @return mixed
     */
    public function getMapping($index=null, $type=null)
    {
        return parent::getMapping($index, $type); // TODO: Change the autogenerated stub
    }




}